[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "comfyui-lora-pipeline"
version = "1.1.2"
description = "Area-based LoRA scheduling and area conditioning wrappers for ComfyUI."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/andreszs/comfyui-lora-pipeline"
Documentation = "https://github.com/andreszs/comfyui-lora-pipeline#readme"
"Bug Tracker" = "https://github.com/andreszs/comfyui-lora-pipeline/issues"

[tool.comfy]
PublisherId = "andreszs"
DisplayName = "LoRA Pipeline"
Icon = ""
Banner = "https://raw.githubusercontent.com/andreszs/comfyui-lora-pipeline/refs/heads/main/assets/banner_112.gif"
